### ISSUE TITLE
Language server problems

### ISSUE THREAD

**Issue by biati-digital** [sciencefidelity/Nova-Astro#2]
Hi, i'm trying to use the extension but i've found some problems.

When enabled "Language server" there's a lot of errors, note that the code in the screenshot is simply the examples included with astro (specifically the portfolio example with no modifications). This errors do not appear in visual studio code.

![CleanShot 2022-08-07 at 01 55 12](https://user-images.githubusercontent.com/1219228/183279085-c8eb271e-4e84-46e8-9583-f087b676f90a.png)

Also when using Jump to definition it always display the same result twice

![CleanShot 2022-08-07 at 01 56 07](https://user-images.githubusercontent.com/1219228/183279114-f83dd718-4106-44b3-9c66-d3884d59346a.png)

Thank's for the extension.

**Comment by sciencefidelity** [comment]
Thanks for letting me know. 
The dependencies hadn't been updated for a while, so we were using an old version of the language server. I've updated and published a new version to the Extension Library. 
Can you update and let me know if the errors go away?

**Comment by biati-digital** [comment]
Updated and working again, thank's for the quick fix. Just our of curiosity, are you still using Nova?
